version: '3.9'

services:
  localstack:
    image: localstack/localstack:3.7.2
    hostname: localstack
    container_name: localstack
    networks:
      - app-network
    environment:
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - SERVICES=sqs
      - SKIP_SSL_CERT_DOWNLOAD=1
      - DISABLE_EVENTS=1
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/_localstack/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  mongodb:
    image: mongo:8.0.15
    container_name: mongodb
    networks:
      - app-network
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "-u", "admin", "-p", "admin", "--quiet" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - app-network
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - app-network
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    networks:
      - app-network
    ports:
      - "16686:16686" # UI
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  message-generator:
    image: golang:1.24.3
    container_name: message-generator
    networks:
      - app-network
    depends_on:
      localstack:
        condition: service_healthy
    restart: always
    environment:
      - QUEUE_NAME=transacoes-financeiras-processadas
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - TOTAL_TRANSACTIONS=300000
      - TOTAL_ACCOUNTS=10000
      - MIN_TRANSACTION_AMOUNT=0
      - MAX_TRANSACTION_AMOUNT=100
      - GOPROXY=https://proxy.golang.org
      - GOSUMDB=sum.golang.org
    working_dir: /home
    command: >
      /bin/sh -c "
        openssl s_client -showcerts -connect proxy.golang.org:443 </dev/null 2>/dev/null |
          awk '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/ { print \$0 }' > /usr/local/share/ca-certificates/ca_bundle.crt &&
        update-ca-certificates &&
        rm -rf /tmp/go && mkdir -p /tmp/go && cd /tmp/go &&
        echo \"cGFja2FnZSBtYWluCn...(long content omitted)\" | base64 -d > message-generator.go &&
        go clean -modcache &&
        go mod init message-generator &&
        go mod tidy &&
        go mod download &&
        go run message-generator.go
      "

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - app-network
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9091:80"
    depends_on:
      - prometheus
      - balance-api-1
      - balance-api-2

  transaction-consumer:
    build:
      context: ./api/transaction-consumer
    container_name: transaction-consumer
    networks:
      - app-network
    depends_on:
      mongodb:
        condition: service_healthy
      localstack:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  balance-api-1:
    build:
      context: ./api/balance-api
    container_name: balance-api-1
    networks:
      - app-network
    ports:
      - "9001:9001"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=9001

  balance-api-2:
    build:
      context: ./api/balance-api
    container_name: balance-api-2
    networks:
      - app-network
    ports:
      - "9002:9001"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=9001

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: